/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Maria
 */
public class Produto extends javax.swing.JFrame {

    /**
     * Creates new form Produto
     */
    public Produto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        categoria = new javax.swing.JLabel();
        cjogos = new javax.swing.JRadioButton();
        cfilmes = new javax.swing.JRadioButton();
        nomeproduto = new javax.swing.JLabel();
        genero = new javax.swing.JLabel();
        cadastrarproduto = new javax.swing.JLabel();
        caixaproduto = new javax.swing.JTextField();
        lista = new javax.swing.JComboBox();
        excluirfilmes = new javax.swing.JComboBox();
        excluirproduto = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        excluirjogos = new javax.swing.JComboBox();
        bcadastrarproduto = new javax.swing.JButton();
        Bexcluirproduto = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        configuracoes1 = new javax.swing.JMenu();
        Produto1 = new javax.swing.JMenuItem();
        Usuario1 = new javax.swing.JMenuItem();
        sobre1 = new javax.swing.JMenu();
        criadores1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Locadora");
        setName("Cproduto"); // NOI18N

        categoria.setText("Categoria:");

        cjogos.setText("Jogos");
        cjogos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cjogosActionPerformed(evt);
            }
        });

        cfilmes.setText("Filmes");

        nomeproduto.setText("Nome:");

        genero.setText("Gênero:");

        cadastrarproduto.setText("Cadastrar Produto");

        caixaproduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaprodutoActionPerformed(evt);
            }
        });

        lista.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ação", "Suspense", "Corrida", "Luta", " ", "\t\t", " " }));
        lista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaActionPerformed(evt);
            }
        });

        excluirfilmes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Filme 1", "Filme 2", "Filme 3", "Filme 4" }));

        excluirproduto.setText("Excluir Produto");

        excluirjogos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jogo 1", "Jogo 2", "Jogo 3", "Jogo 4" }));

        bcadastrarproduto.setText("Cadastrar Produto");

        Bexcluirproduto.setText("Excluir Produto");

        configuracoes1.setText("Configurações");

        Produto1.setText("Produto");
        configuracoes1.add(Produto1);

        Usuario1.setText("Usuário");
        configuracoes1.add(Usuario1);

        jMenuBar1.add(configuracoes1);

        sobre1.setText("Sobre");

        criadores1.setText("Criadores");
        sobre1.add(criadores1);

        jMenuBar1.add(sobre1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nomeproduto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(caixaproduto, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(categoria)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cjogos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cfilmes))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(cadastrarproduto))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(genero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(bcadastrarproduto)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Bexcluirproduto)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(excluirfilmes, 0, 106, Short.MAX_VALUE)
                                .addComponent(excluirjogos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(excluirproduto)))
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(cadastrarproduto))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(excluirproduto)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cfilmes)
                    .addComponent(cjogos)
                    .addComponent(categoria)
                    .addComponent(excluirfilmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomeproduto)
                            .addComponent(caixaproduto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(genero, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(excluirjogos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Bexcluirproduto)))
                .addGap(18, 18, 18)
                .addComponent(bcadastrarproduto)
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cjogosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cjogosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cjogosActionPerformed

    private void caixaprodutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaprodutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixaprodutoActionPerformed

    private void listaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Produto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bexcluirproduto;
    private javax.swing.JMenuItem Produto1;
    private javax.swing.JMenuItem Usuario1;
    private javax.swing.JButton bcadastrarproduto;
    private javax.swing.JLabel cadastrarproduto;
    private javax.swing.JTextField caixaproduto;
    private javax.swing.JLabel categoria;
    private javax.swing.JRadioButton cfilmes;
    private javax.swing.JRadioButton cjogos;
    private javax.swing.JMenu configuracoes1;
    private javax.swing.JMenuItem criadores1;
    private javax.swing.JComboBox excluirfilmes;
    private javax.swing.JComboBox excluirjogos;
    private javax.swing.JLabel excluirproduto;
    private javax.swing.JLabel genero;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox lista;
    private javax.swing.JLabel nomeproduto;
    private javax.swing.JMenu sobre1;
    // End of variables declaration//GEN-END:variables
}
